### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by efoosag** [t-bello7/micro-capstone-1#9]
### Very Good Job 👋 
Good Code Organization
Easy to read

### Suggestion

- Use main tag to cover the content until the footer tag ad then use section tag inside the main tag.
- You could use bootstrap framework for the navigation.
- You could include a link back to the home page from the about page.

**Comment by t-bello7** [comment]
Thank you 🙏  @efoosag for the review.
I would work on the suggestions you gave to improve the project.
